services:
  # Service pour Apache + PHP
  web:
    build: .
    container_name: php-apache
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    networks:
      - app-network

  # Service pour MySQL
  db:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: utilisateurs
    volumes:
      - db-data:/var/lib/mysql
      - ./src/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  # Service pour phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8010:80"
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge